install:
  - yarn install --production=false

script:
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAIEAAWOKYBJ2NXANQ
  secret_access_key:
    secure: pjse6H1G28s3XxHtCHRNFZJV1Ouxpxa1pYr7l0PpTME79sqmE93x+sx2Pte8mDRFfNYAy/mzDhlsEKnmBWnmJXyTptOG4RDZVpJTOg5Vv5wDH2DDQHb82/c47WVLCQ5sUfUPTVrb8G9JET+ZdHV2u/jQNwGIYZ32LNXjXOEdw3ZhR5R0nA7C+ilvnRJo1eh34bOiCdYyvOdV3P219+aIOPcHaUne96GXUs06EYi7Z1vNMlAyknulJgCnmErbWMMiEHmOK1g4256hYUJlh/9T5dBw+cesD7GLdRKxRlm1rJKH6d14S8dx53amNll+OPTAqYlCBz0oQJ8Pqcbajl9sEHTBWbTYh1eep4YjDtclGiJrO+xaw3IgG8B41pCwNQx/5W+GF7zLWWwfqCK2xvXti0woWIkSn7wXjAYgUfG2n/N4ipLL90coIS0ycLE6KbBIY6REKB0ktV0t6m01bjgmmThNYM0JkXRfpXXbyOhD52m3xyDCkCiyE05/6NNML3mUfPxlRzG1eMZbWEgRTpPNzNIX8aTL0HiLgNo000jorTTZJi2mbqjWq3qNeWDpu66LeBdPjjUiWb2kGQJ9pCPCEwffzU7pCdel7TCS6lY+Xoq9ovGArvdnH4y0roCeGmFcH4nuc8wK6rf3uw4jGQ2VGDw8fqglOaNAJo1RUhmlt50=
  bucket: jimiford.com
  skip_cleanup: true
  local_dir: build
  region: us-east-1